version: '3'
services:
  pyvirt:
    image: dariusbakunas/pyvirt-api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
     - FLASK_CONFIGURATION=development
    container_name: pyvirt-api
    ports:
     - "9999:80"
    volumes:
     - /etc/pki/libvirt:/etc/pki/libvirt
     - /etc/pki/CA:/etc/pki/CA
     - ./instance:/app/instance