version: '3'
services:
  redis:
    image: redis:3
    ports:
      - 6379:6379
    networks:
      - pyvirt
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: pyvirt-api-redis
  uwsgi:
    image: dariusbakunas/pyvirt-api:latest
    networks:
      - pyvirt
    environment:
      - FLASK_CONFIGURATION=development
    container_name: pyvirt-api-uwsgi
    ports:
      - 9990:8000
    depends_on:
      - redis
    volumes:
      - /etc/pki/libvirt:/etc/pki/libvirt:ro
      - /etc/pki/CA:/etc/pki/CA:ro
      - ./instance:/app/instance:ro
  nginx:
    image: nginx:1.13-alpine
    container_name: pyvirt-api-nginx
    networks:
      - pyvirt
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - uwsgi
    ports:
      - 9999:9999

networks:
  pyvirt: