version: '3'
services:
  uwsgi:
    image: dariusbakunas/pyvirt-api:latest
    environment:
     - FLASK_CONFIGURATION=development
    container_name: pyvirt-api-uwsgi
    ports:
     - 3031:3031
     - 3032:3032
    volumes:
     - /etc/pki/libvirt:/etc/pki/libvirt:ro
     - /etc/pki/CA:/etc/pki/CA:ro
     - ./instance:/app/instance:ro
  nginx:
    image: nginx:1.13-alpine
    container_name: pyvirt-api-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - uwsgi
    ports:
      - 9999:9999